### ISSUE TITLE
Support for YY as well as YYYY on sample collection date

### ISSUE THREAD

**Issue by wasade** [biocore/microsetta-interface#14]
In some cases, users appear to be able to enter in YY instead of YYYY for the date.

```bash
[2020-08-19 09:20:16 -0700] [13156] [ERROR] Exception on /accounts/f9db6c2e-ed49-41fa-a97a-5a35bb14a7ae/sources/52b7b032-074e-4beb-8340-262403877256/samples/913193c7-d1bd-40ec-bbae-a61d4404efa7 [POST]
Traceback (most recent call last):
  File "/Users/api_user/miniconda3/envs/microsetta-interface/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/api_user/miniconda3/envs/microsetta-interface/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/api_user/miniconda3/envs/microsetta-interface/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/api_user/miniconda3/envs/microsetta-interface/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/api_user/miniconda3/envs/microsetta-interface/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/api_user/miniconda3/envs/microsetta-interface/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/api_user/miniconda3/envs/microsetta-interface/lib/python3.8/site-packages/connexion/decorators/decorator.py", line 48, in wrapper
    response = function(request)
  File "/Users/api_user/miniconda3/envs/microsetta-interface/lib/python3.8/site-packages/connexion/decorators/uri_parsing.py", line 144, in wrapper
    response = function(request)
  File "/Users/api_user/miniconda3/envs/microsetta-interface/lib/python3.8/site-packages/connexion/decorators/validation.py", line 184, in wrapper
    response = function(request)
  File "/Users/api_user/miniconda3/envs/microsetta-interface/lib/python3.8/site-packages/connexion/decorators/validation.py", line 384, in wrapper
    return function(request)
  File "/Users/api_user/miniconda3/envs/microsetta-interface/lib/python3.8/site-packages/connexion/decorators/produces.py", line 38, in wrapper
    response = function(request)
  File "/Users/api_user/miniconda3/envs/microsetta-interface/lib/python3.8/site-packages/connexion/decorators/response.py", line 103, in wrapper
    response = function(request)
  File "/Users/api_user/miniconda3/envs/microsetta-interface/lib/python3.8/site-packages/connexion/decorators/parameter.py", line 121, in wrapper
    return function(**kwargs)
  File "/Users/api_user/miniconda3/envs/microsetta-interface/lib/python3.8/site-packages/microsetta_interface/implementation.py", line 319, in wrapper
    return func(**kwargs)
  File "/Users/api_user/miniconda3/envs/microsetta-interface/lib/python3.8/site-packages/microsetta_interface/implementation.py", line 945, in post_update_sample
    sample_datetime = datetime.strptime(date_and_time, "%m/%d/%Y %I:%M %p")
  File "/Users/api_user/miniconda3/envs/microsetta-interface/lib/python3.8/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/Users/api_user/miniconda3/envs/microsetta-interface/lib/python3.8/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '8/18/20 5:00 PM' does not match format '%m/%d/%Y %I:%M %p'
```

**Comment by wasade** [comment]
Duplicate of #2
